- hosts: wildfly
  become: yes
  tasks:
    - name: Install Java
      yum:
        name: java-17
        state: present

    - name: Download WildFly
      get_url:
        url: https://github.com/wildfly/wildfly/releases/download/30.0.0.Final/wildfly-30.0.0.Final.tar.gz
        dest: /opt/

    - name: Extract WildFly
      unarchive:
        src: /opt/wildfly-30.0.0.Final.tar.gz
        dest: /opt/
        remote_src: yes
